### ISSUE TITLE
代码文件不全

### ISSUE THREAD

**Issue by wzjjie** [rqi7/Unsupervised_Electricity_Theft_Detection#2]
func.py里面函数缺少，fcmeans是需要下载某个library吗

**Comment by rqi7** [comment]
是的
https://github.com/omadson/fuzzy-c-means

**Comment by wzjjie** [comment]
您好，感谢您的回答。readraw.py中调用了func.py中的func.find_con_0和func.tsrt，但是我在func.py中并没有看见，可以请您分享一下代码和相关注释吗，谢谢。

**Comment by rqi7** [comment]
> 您好，感谢您的回答。readraw.py中调用了func.py中的func.find_con_0和func.tsrt，但是我在func.py中并没有看见，可以请您分享一下代码和相关注释吗，谢谢。

Updated

**Comment by wzjjie** [comment]
感谢
