### ISSUE TITLE
数据集的划分

### ISSUE THREAD

**Issue by wzjjie** [rqi7/Unsupervised_Electricity_Theft_Detection#3]
在文章中，您提到“a portion of users in an area are chosen as electricity thieves”，我很好奇这一部分的比例。因为在main.py中，您直接给出了"data/FDI" + str(FDI_TYPE) + "/reading.csv"，"data/FDI" + str(FDI_TYPE) + "/fraudulent_user.csv"，"data/observed/observer_reading.csv"，这几个输入文件，但是代码中并没有给出其生成方式，希望您能更新一下代码，谢谢。

**Comment by wzjjie** [comment]
您好，在阅读代码的时候，我产生了一个问题。在func.py中的FDI6里，l.iloc[[t]] = np.mean(l) * random.uniform(0.20001, 0.79999)的写法我觉得有问题。在l不断更替时，mean（l）也是个不断更新的值，这和文章中的第六种攻击方式（mean（l）应该是个定值）有偏差。不知道您怎么看。

**Comment by rqi7** [comment]
> 在文章中，您提到“a portion of users in an area are chosen as electricity thieves”，我很好奇这一部分的比例。因为在main.py中，您直接给出了"data/FDI" + str(FDI_TYPE) + "/reading.csv"，"data/FDI" + str(FDI_TYPE) + "/fraudulent_user.csv"，"data/observed/observer_reading.csv"，这几个输入文件，但是代码中并没有给出其生成方式，希望您能更新一下代码，谢谢。

 这些csv文件是由tampered_data.py 生成的，我没有固定名字因为每个人用的路径名可能不一样，相关评论已更新

**Comment by rqi7** [comment]
> 您好，在阅读代码的时候，我产生了一个问题。在func.py中的FDI6里，l.iloc[[t]] = np.mean(l) * random.uniform(0.20001, 0.79999)的写法我觉得有问题。在l不断更替时，mean（l）也是个不断更新的值，这和文章中的第六种攻击方式（mean（l）应该是个定值）有偏差。不知道您怎么看。

感谢指出，你是对的，相关代码已更新
